// NOTE: This file is auto-generated by Rotor
import { Bansa, listen } from "https://deno.land/x/bansa@0.0.4/mod.ts"

const App = Bansa;

App['/'] = (req: Request) => {
        return new Response(`User-Agent: ${req.headers.get('User-Agent')}`);
    } 
listen({ port: 8080 });